name: clawdshield

services:
  db:
    container_name: clawdshield_postgres_db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - clawdshield_postgres_data:/var/lib/postgresql/data

volumes:
  clawdshield_postgres_data: {}
